### ISSUE TITLE
Add Casbin as the authorization (AuthZ) plugin for dotweb

### ISSUE THREAD

**Issue by hsluoyz** [devfeel/middleware#1]
Hi, I'm the author of [Casbin](https://github.com/casbin/casbin), a Go library for authorization based on access control policy. Casbin supports multiple access control models like ACL, BLP, RBAC. The access control rules can be persisted into files, DB.

A user of mine asks me if I can add the support for dotweb on the issues: https://github.com/casbin/casbin/issues/21

I think dotweb is very good, and I found this middleware repo. So what do you think by adding Casbin as an authorization middleware? Thanks!

**Comment by devfeel** [comment]
感谢关注，很高心能够得到你的支持，对于casbin的中间件，欢迎之至！ 另外，方便的话，可以交换下联系方式：）  欢迎加入Q群 193409346

**Comment by hsluoyz** [comment]
好的，已经加入QQ群。

另外已经针对该issue提交PR: https://github.com/devfeel/middleware/pull/2

**Comment by hsluoyz** [comment]
谢谢merge
