### ISSUE TITLE
example里的accesslog示例使用的accesslog中间件build时报错

### ISSUE THREAD

**Issue by gnuos** [devfeel/middleware#5]
我是直接build了 example 里的 accesslog.go ，但是 build 的时候报 `# github.com/devfeel/middleware/accesslog
/var/lib/go/src/github.com/devfeel/middleware/accesslog/accesslog.go:28:17: logger.Logger().Log undefined (type logger.AppLog has no field or method Log)` 错误，我检查了一下 `github.com/devfeel/dotweb/logger` 的 `Logger()` 函数和 `Applog` 结构，我发现 `Applog` 里面没有 `Log()` 方法，但是在 `accesslog` 中间件里调用了，所以会报错。

**Comment by devfeel** [comment]
thanks, fixed on 2017-06-09
